version: '3.8'

services:
  indexer:
    build:
      context: ./Indexer
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: blockchain
      DB_USER: user
      DB_PASS: password
    restart: unless-stopped
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: blockchain
      DB_USER: user
      DB_PASS: password
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blockchain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
